# Generated by Django 4.1.1 on 2022-09-19 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyWatchedList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('watched', models.CharField(max_length=255)),
                ('title', models.BigIntegerField()),
                ('rating', models.TextField()),
                ('release_date', models.TextField()),
                ('review', models.TextField()),
            ],
        ),
    ]
